USE cce;
CREATE TABLE IF NOT EXISTS 3DModels
(
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  name VARCHAR(150) NOT NULL,
  url VARCHAR(300) NOT NULL UNIQUE,
  thumbnail VARCHAR(300) UNICODE,
  tagLabel VARCHAR(300),
  creationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  version SMALLINT UNSIGNED NOT NULL,
  isCurrentVersion BOOLEAN NOT NULL DEFAULT FALSE,
  versionComment VARCHAR(500),
  PRIMARY KEY (id)
);

